wso2/vscode-extensions

common/scripts/env-webpack-helper.js
workspaces/ballerina/ballerina-extension/webpack.config.js
workspaces/mi/mi-extension/webpack.config.js
workspaces/wso2-platform/wso2-platform-extension/webpack.config.js

Enhance webpack environment variable handling to support fallback logic:
- Check .env file first for variable values  
- If .env declares a variable but has no value, fallback to process.env
- Only define variables that are explicitly declared in .env file
- Prevents webpack from replacing undefined variables, maintaining runtime flexibility
This allows developers to declare environment variables in .env with empty values and have webpack automatically use runtime environment values as fallback, while still maintaining control over which variables get replaced during build time.

Add fallback support for environment variables from .env to process.env

---

workspaces/ballerina/ballerina-extension/package.json

This pull request introduces a VSCode setting to show or hide the experimental sequence diagram feature.

Add VSCode Setting for Sequence Diagram Visibility

---

common/scripts/env-webpack-helper.js
workspaces/ballerina/ballerina-extension/webpack.config.js
workspaces/mi/mi-extension/webpack.config.js
workspaces/wso2-platform/wso2-platform-extension/webpack.config.js

This pull request updates the build process to show warnings for missing environment variables instead of causing the build to fail. This allows processes like pull request checks, which lack configured environment variables, to complete successfully. The warning logs will still help developers identify any missing variables.

Warn on Missing Environment Variables and Continue Build

---

workspaces/bi/bi-extension/src/test/e2e-playwright-tests/utils.ts

This pr adds a util to address an intermittent test failure that occurred during the project setup phase in the BI extension tests
> Link(s) to product documentation that addresses …

Fix intermittent test failure on projectSetup

---

workspaces/ballerina/ballerina-extension/src/stateMachine.ts
workspaces/ballerina/ballerina-extension/src/views/visualizer/webview.ts
workspaces/ballerina/ballerina-visualizer/src/MainPanel.tsx
workspaces/ballerina/ballerina-visualizer/src/Visualizer.tsx

Fixes https://github.com/wso2/product-ballerina-integrator/issues/684
Views
- Initial Loading View on webview creation
- Loading view on activating LS
- Loading view on main panel render
> Brief description of the new feature or bug fix as it will appear in the release …

Open webview and add loading views before activating LS

---

workspaces/ballerina/ballerina-extension/package.json

This pull request adds a missing VSCode extension setting to enable or disable AI-powered suggestions within the flow diagram.
Fixed: https://github.com/wso2/product-ballerina-integrator/issues/719

Add VSCode Setting for AI Suggestions in Flow Diagram

---

workspaces/ballerina/ballerina-extension/src/features/project/cmds/configRun.ts
workspaces/ballerina/ballerina-extension/src/rpc-managers/bi-diagram/rpc-manager.ts

Fix config.toml create command

---

workspaces/ballerina/ballerina-extension/package.json

This pull request reverts the previous change that restricted the download-ls script to download only pre-released versions of the language server.

Update download-ls script to download both released and pre-released versions

---

workspaces/mi/mi-extension/package.json
workspaces/mi/mi-visualizer/src/constants/index.ts
workspaces/mi/mi-visualizer/src/views/UnsupportedProject/index.tsx

Previously the **Migrate Project** button appeared in the side panel. However when we introduce multi workspace, it no longer can be displayed in the side panel. Hence this PR will introduce following changes.
* **Migrate Project** button removed from side panel
* **Migrate Project** button is moved to the Unsupported Project page
Previous View 
New View 
Fixes: https://github.com/wso2/mi-vscode/issues/1190

Move migrate project button to unsupported project page

---

workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/rpc-manager.ts
workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/common-utils.ts

> Temporarily disable  the on-the-fly mappings options in BI Inline datamapper until LS supports
> Additionally, refactor the delete mapping RPC method promise handling

Temporarily disable  the on-the-fly mappings options in BI Inline datamapper

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/Overview/index.tsx

Add expand/collapse icon instead of circle bullet in deployment options

---

workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
workspaces/ballerina/inline-data-mapper/src/components/DataMapper/DataMapper.tsx
workspaces/ballerina/inline-data-mapper/src/components/DataMapper/Header/HeaderBreadcrumb.tsx
workspaces/ballerina/inline-data-mapper/src/components/Diagram/LinkState/CreateLinkState.ts
workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/Input/InputNode.ts
workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/diagram-utils.ts
workspaces/ballerina/inline-data-mapper/src/components/Hooks/index.tsx

$title
This PR also fix:
- deleting multilined expressions
- selecting links after inputs expand by clicking on input fields

[Inline Data Mapper] Preserve node scroll position on mapping updates

---

workspaces/mi/mi-extension/src/util/migrationUtils.ts

With this PR following changes will be interoduced:
- If currently in a workspace: Open the newly created projects in the existing workspace.
- If not in a workspace and multiple projects are created: Switch to workspace mode and open the new projects together.
- If not in a workspace and only one project is created: Keep the existing behavior and open the single project directly (without creating a workspace).
Fixes: https://github.com/wso2/mi-vscode/issues/1202

Support opening migrated projects in a workspace if necessary.

---

workspaces/ballerina/ballerina-extension/src/features/ai/utils.ts
workspaces/ballerina/ballerina-extension/src/features/natural-programming/utils.ts
workspaces/ballerina/ballerina-extension/src/utils/ai/auth.ts

Related Issue: [wso2/product-ballerina-integrator#822](https://github.com/wso2/product-ballerina-integrator/issues/822)
This PR refactors the `addDefaultModelConfig` function to ensure that the configuration values for the WSO2 Model Provider are added or updated correctly without duplicating entries, particularly the accessToken.
**Current behavior:** When an accessToken is already set in the config, using the "Ballerina: Configure Default WSO2 Model Provider" command results in a duplicate accessToken line being added.
https://github.com/user-attachments/assets/ab76c361-e9e4-4223-b765-136fbdc9095a
Changes Include:
The updated logic now handles the following scenarios:
**1. No existing config**
Adds the full configuration block:
```toml
[ballerina.ai.wso2ProviderConfig]
serviceUrl = …
```

Fix duplicate `accessToken` when configuring default WSO2 Model Provider

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AddMcpServer.tsx

> When using the `getNodeTemplate` API with `ballerina/mcp` configs it returns all the necessary fields. But in the `info` field, it contains an invalid `defaultValue` field. This PR is remove that unnecessary config

Remove redundant default value field in mcp toolkit

---

workspaces/ballerina/ballerina-core/src/interfaces/bi.ts
workspaces/ballerina/ballerina-side-panel/src/components/Form/index.tsx
workspaces/ballerina/ballerina-side-panel/src/components/editors/CustomDropdownEditor.tsx
workspaces/ballerina/ballerina-side-panel/src/components/editors/DropdownEditor.tsx
workspaces/ballerina/ballerina-side-panel/src/components/editors/EditorFactory.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGenerator/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/VectorKnowledgeBaseForm/index.tsx

This PR streamlines the user workflow for creating a vector knowledgebase.
Previously, a user had to create a vector store and an embedding provider as separate, prerequisite steps. This update allows the user to create both the vector store and the embedding provider directly from within the knowledgebase creation form, simplifying the entire process into a single step.
Tracking Issue: https://github.com/wso2/product-ballerina-integrator/issues/800
https://github.com/user-attachments/assets/9b08acec-217a-4848-bb8c-49b34e41ec29

Refactor vector knowledgebase creation workflow

---

workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
workspaces/ballerina/ballerina-extension/package.json
workspaces/ballerina/ballerina-extension/src/core/extension.ts
workspaces/ballerina/ballerina-extension/src/core/preferences.ts
workspaces/ballerina/ballerina-extension/src/rpc-managers/bi-diagram/rpc-manager.ts

This flag will be appended to each search query, allowing the LS to query the central with the organization specified in the `Ballerina.toml`.
Addresses https://github.com/wso2/product-ballerina-integrator/issues/758

Add an extension setting to include the current organization in the search

---

workspaces/ballerina/data-mapper-view/src/components/Diagram/utils/dm-utils.ts

$title
Related to: https://github.com/wso2/product-ballerina-integrator/issues/678

[Ballerina Data Mapper] Avoid creating binary expressions for float/decimal targets with default values

---

workspaces/ballerina/ballerina-visualizer/src/utils/bi.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGenerator/index.tsx

Fixes an issue where variable form fields were reordered when a user attempted to edit a variable node. This is achieved by refactoring enrichFormPropertiesWithValueConstraint to correctly copy values from formProperties to formTemplateProperties.
Related Issue: https://github.com/wso2/product-ballerina-integrator/issues/970

Fix variable form field reorder on edit

---

workspaces/mi/mi-extension/src/util/migrationUtils.ts

Previously it was capturing `projects` tags as well. But we need to only capture `project` tags.

Fix capturing project tags from resolved pom content

---

workspaces/ballerina/ballerina-extension/package.json
workspaces/ballerina/ballerina-extension/src/core/extension.ts
workspaces/ballerina/ballerina-extension/src/core/preferences.ts
workspaces/ballerina/ballerina-extension/src/rpc-managers/bi-diagram/rpc-manager.ts
workspaces/ballerina/bi-diagram/src/components/NodeIcon/index.tsx
workspaces/common-libs/font-wso2-vscode/src/icons/bi-data-table.svg

Hides the following AI RAG node types by default: `Chunker, Vector Store, Embedding Provider, and Recursive Document Chunker`. These nodes can be enabled by setting `ballerina.showAdvancedAiNodes` to true in the Ballerina extension.
**Task**: https://github.com/wso2/product-ballerina-integrator/issues/1019
https://github.com/user-attachments/assets/6cc0a3af-dff8-4d14-9689-8ec8fe17b5a4

Hide AI RAG nodes as advanced nodes

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Components/ExpandableList.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/Variables.tsx
workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/components/Common/SlidingPane/index.tsx

The helper pane currently crops longer content in variables dropdown, making it difficult for users to view the full suggestion.  
**Resolves:** [Issue: #1110]
Introduce a solution that ensures longer content in the helper pane is accessible without breaking the current UI. This includes trimming text in the visible area while allowing full content on hover.
- Truncate long text in the helper pane variables for better UI consistency.
- Implement a hover-based expansion that displays the complete text on hover.

fix variables label trimming issue

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGeneratorNew/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/GraphQLDiagram/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/TypeDiagram/index.tsx

Fix the incorrect options shown in the **Create New Type** flow in `TypeHelper` within the GraphQL context.  
**Resolves:** Issue – [wso2/product-ballerina-integrator#](https://github.com/wso2/product-ballerina-integrator/issues/1120)1120
- Ensure field types correctly display **Object types (Service classes)** and **Input Object types (Records)**.  
- Updated the `TypeHelper` logic to differentiate between graphql and other forms.

fix graphql typeHelper displays incorrect options

---

workspaces/ballerina/ballerina-core/src/interfaces/bi.ts
workspaces/ballerina/ballerina-side-panel/src/components/editors/TypeEditor.tsx
workspaces/ballerina/ballerina-visualizer/src/components/Modal/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGenerator/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGeneratorNew/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/GraphQLDiagram/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/TypeDiagram/index.tsx
workspaces/ballerina/type-editor/src/TypeEditor/Tabs/TypeCreatorTab.tsx
workspaces/ballerina/type-editor/src/TypeHelper/TypeHelper.tsx

This PR addresses two main issues:
1. **Type Editor not opening** on the type diagram.
2. **Build errors** that were blocking successful compilation.
Resolves: https://github.com/wso2/product-ballerina-integrator/issues/1122, https://github.com/wso2/product-ballerina-integrator/issues/1154
- Ensure that the Type Editor opens correctly when interacting with the type diagram.
- Eliminate build errors to restore a stable development workflow.
- Improve overall reliability of the type diagram functionality.
- Investigated the root cause of the Type Editor not opening and applied fixes to the event handling logic in the type diagram.
- Resolved build errors by fixing incompatible code segments and adding mission props and implementations.
- Verified that the Type Editor now consistently opens …

Fix type crease modal

---

workspaces/ballerina/ballerina-visualizer/src/utils/bi.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/DeclareVariableForm/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGenerator/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGeneratorNew/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPane/ConfigureRecordPage.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/Configurables.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/RecordConfigModal.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/index.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/TypeEditor/utils.tsx
workspaces/ballerina/type-editor/src/TypeHelper/index.tsx
workspaces/common-libs/ui-toolkit/src/components/TabPanel/TabPanel.tsx

> This PR introduces recordConfig support for user-defined types in the Ballerina Integrator extension. Currently, recordConfig is not properly recognized or handled when applied to user-defined types, limiting the ability to configure such types consistently within the extension. Additionally it changes the styling in type creator and also the breadcrumbs.
> Enable full support for recordConfig usage in user-defined types.
> Match the typeCreator color to match the current theme.
> Breadcrumb now only show the steps only when there are atleast two steps present
> Extended the type handling logic to recognize and apply recordConfig annotations for user-defined types.
> Change color of components using ThemeColors

Type creator color0change

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/index.tsx
workspaces/ballerina/type-editor/src/TypeHelper/TypeHelper.tsx

Previously:  
- The search bar input in the **TypeHelper** search (inside the type field) could not be focused properly, preventing users from interacting with it.  
- When the **RecordConfig** view was open, the helper pane was not closing, causing the two views to overlap and making the UI cluttered.  
- Allow users to focus and interact with the TypeHelper search bar input without issues.  
- Automatically close the helper pane when the RecordConfig view is open, ensuring a clean and non-overlapping UI experience.  
- Added a necessary component ID to properly track and manage the focus state of the TypeHelper search input.  
- Updated the view handling logic so that opening the RecordConfig view now closes the helper pane, avoiding overlapping.  
- Verified the fixes by:  
- …

Fix cannot focus search bar input in TypeHelper search in typeFIeld and helperpane not closing when opening recordCOnfig view

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/Configurables.tsx
workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/components/Common/SlidingPane/index.tsx

This PR addresses two issues observed in the **Helper Pane** and **Sliding Pane** components:  
1. **Light theme readability** – Items in the Helper Pane were not easily visible in light themes due to low contrast.  
2. **Pane closing behavior** – The Helper Pane remained open even after a configurable item was selected, leading to a less smooth user experience.  
Resolves: https://github.com/wso2/product-ballerina-integrator/issues/1298
Resolves: https://github.com/wso2/product-ballerina-integrator/issues/1297
- Improve readability of Helper Pane items across themes, ensuring consistent visibility in both dark and light modes.  
- Close the Helper Pane automatically when a configurable item is clicked, providing a more intuitive and user-friendly flow.  
- Updated the **Helper Pane item …

Fix helperpane item light color

---

workspaces/mi/mi-extension/src/util/onboardingUtils.ts

Previously it was indicated as an error message. It is now indicated as a warning message. 
Fixes: https://github.com/wso2/mi-vscode/issues/1257

Indicate warning message when MI version is not found

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/RecordConfigModal.tsx

When the record configuration checkbox model cannot be retrieved, the UI currently displays the following message:  
> *“Record construction assistance is unavailable.”*  
Previously, this message also included a reference to the **Suggestions tab**, which is no longer part of the UI. Removing that part ensures the message is accurate and not misleading.  
Resolves: https://github.com/wso2/product-ballerina-integrator/issues/1323
- Remove outdated references from the invalid record configuration message.  
- Ensure the updated message reflects the current UI flow.  
- Improve user experience by providing clear and correct feedback.  
- Identify the component responsible for rendering the invalid record configuration message.  
- Update the string by removing the outdated reference to the …

fix incorrect error message in record config editor

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx

This PR fixes an issue in the Data Mapper where newly created variables were not reflected in the **Expression Helper variables list** after navigating back.  
Previously, when a user clicked **Open in Data Mapper**, created a new variable, and then navigated back, the new variable would not appear in the variables list, causing inconsistency between the editor state and the helper.  
- Ensure that newly created variables are correctly updated and displayed in the **Expression Helper variables list** after returning from the Data Mapper.  
- Provide a consistent and reliable user experience when working with variables across the Data Mapper and Expression Helper.  
- Updated the state synchronization between the Data Mapper and Expression Helper.  
- Ensured that variable updates are …

fix data mapper open does not update the variables list

---

workspaces/ballerina/type-editor/src/TypeHelper/TypeHelper.tsx

Previously, when selecting a type item from the type helper in the type editor, the existing editor value was always replaced. This caused issues when users were working with operators like `|` or `readonly &`, as they were unable to conveniently combine multiple types using those operators.
- Allow users to seamlessly add new type items without losing existing ones when operators (`|`, `readonly &`) are being used in the type editor.
- Improve usability of the type editor by enabling operator-based concatenation of types.
- Updated the type editor logic to detect when the current value includes supported operators (`|`, `readonly &`).
- Instead of replacing the existing value, the newly selected type item is concatenated to the current value, allowing users to construct complex type …

type helper do not concat the type when using operators

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/RecordConfigView.tsx
workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/index.tsx

Fix an issue where the record configuration content was being cropped inside the popup, making it difficult for users to view or interact with the full content. 
Ensure that the record configuration content is fully visible within the popup. Improve the usability and readability of the configuration UI so users can see and interact with all fields without content being cut off.
- Adjusted the popup layout and styling to properly accommodate the full content of record configurations.  
- Tested with different record sizes to ensure content is no longer cropped.  
- Improved scroll behavior and resizing to handle large or deeply nested records.

Fix record config popup crops the content

---

workspaces/ballerina/ballerina-visualizer/src/views/BI/HelperPaneNew/Views/RecordConfigView.tsx

Fix an issue where the record configuration content was being cropped inside the popup, making it difficult for users to view or interact with the full content. 
Ensure that the record configuration content is fully visible within the popup. Improve the usability and readability of the configuration UI so users can see and interact with all fields without content being cut off.
- Adjusted the popup layout and styling to properly accommodate the full content of record configurations.  
- Tested with different record sizes to ensure content is no longer cropped.  
- Improved scroll behavior and resizing to handle large or deeply nested records.

fix recordConfig not scrollable in popup

---

workspaces/ballerina/type-editor/src/TypeHelper/index.tsx
workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/constants/form.ts

This PR fixes an issue with the **Helper Pane width** in the **MI (Micro Integrator)** editor.  
Previously, the width was being incorrectly set due to an outdated constant that overrode the responsive layout behavior.  
Resolves: _(https://github.com/wso2/product-ballerina-integrator/issues/1433)_
---
- Restore the intended **Helper Pane width** behavior.  
- Ensure consistent layout alignment across all editors by resetting the old width constant used specifically for the MI editor.  
---
- Changed the constant value to the correct value that was used before expression editor changes.

Fix Mi Helperpane width 
