wso2/vscode-extensions

- workspaces/ballerina/ballerina-extension/package.json
- workspaces/ballerina/ballerina-extension/scripts/download-ls.js
- workspaces/mi/mi-extension/scripts/download-ls.js
> $subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
> Use Github token to download ls

- .github/workflows/build.yml
- .github/workflows/cache-cleanup.yml
> Add workflow improvements

- workspaces/ballerina/type-diagram/src/components/entity-relationship/EntityNode/EntityHead/EntityHead.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/TypeEditor.tsx
- workspaces/ballerina/type-editor/src/components/FileSelector/index.tsx
- workspaces/common-libs/font-wso2-vscode/src/icons/bi-import.svg
This pr,
- Make imported nodes read-only and display an importedType label (https://github.com/wso2/product-ballerina-integrator/issues/651)
- Update the import icon
https://github.com/user-attachments/assets/08716cd5-a0a9-4199-be04-a5f42d1b15dd
> Brief description of …
> Update imported types as view only nodes

- workspaces/ballerina/bi-diagram/src/components/DiagramCanvas.tsx
- workspaces/ballerina/bi-diagram/src/components/NodeLink/NodeLinkModel.ts
- workspaces/ballerina/bi-diagram/src/components/NodeLink/NodeLinkWidget.tsx
- workspaces/ballerina/bi-diagram/src/components/nodes/EmptyNode/EmptyNodeModel.ts
- workspaces/ballerina/bi-diagram/src/components/nodes/EmptyNode/EmptyNodeWidget.tsx
- workspaces/ballerina/bi-diagram/src/visitors/NodeFactoryVisitor.ts
- workspaces/bi/bi-extension/src/test/e2e-playwright-tests/components/Diagram.ts
- workspaces/bi/bi-extension/src/test/e2e-playwright-tests/components/SidePanel.ts
- workspaces/bi/bi-extension/src/test/e2e-playwright-tests/expression-editor/expression-editor.spec.ts
- workspaces/common-libs/ui-toolkit/src/components/SidePanel/SidePanel.tsx
This PR includes tests utils related to BI Diagram, SidePanel and Expression Editor.
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
> Implement tests utils for BI

- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-extension/src/views/visualizer/webview.ts
> $subject
https://github.com/user-attachments/assets/8ba60a6a-e36e-479f-bfe8-ba82db63b3af
> Refresh datamapper when code file changed

- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
Fixes: https://github.com/wso2/product-ballerina-integrator/issues/761
> Brief description of the new feature or …
> Enhance artifact identification in BIFlowDiagram by allowing search by id and name

- workspaces/ballerina/ballerina-extension/src/views/visualizer/webview.ts
This pull request updates the title of the initial loader.
> Update Initial Loader Title

- common/config/rush/pnpm-lock.yaml
- workspaces/ballerina/type-diagram/package.json
- workspaces/ballerina/type-diagram/src/components/Controls/DiagramControls.tsx
- workspaces/mi/mi-diagram/package.json
Downgraded the html-to-image library to address an issue in the latest version where SVG elements were not rendered correctly, causing links in the downloaded image to be missing.
issue https://github.com/wso2/product-ballerina-integrator/issues/713
> Brief description …
> Fix missing links in downloaded image

- workspaces/mi/mi-extension/package.json
- workspaces/mi/mi-extension/src/extension.ts
- workspaces/mi/mi-extension/src/project-explorer/project-explorer-provider.ts
- workspaces/mi/mi-extension/src/stateMachine.ts
- workspaces/mi/mi-extension/src/visualizer/activate.ts
- workspaces/mi/mi-visualizer/src/MainPanel.tsx
- workspaces/mi/mi-visualizer/src/PopupPanel.tsx
This PR will fix the issues mentioned in https://github.com/wso2/mi-vscode/issues/1148
> Fix issues in the MI Extension

- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-extension/src/views/visualizer/webview.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Label/ExpressionLabelWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Link/DataMapperLink/DataMapperLink.ts
> [Inline Data Mapper] Handle refreshing in both text and ui based edits

- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-visualizer/src/views/InlineDataMapper/DataMapperView.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/InlineDataMapper/utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ArrayOutput/ArrayOuptutFieldWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ArrayOutput/ArrayOutputWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/Input/InputNodeTreeItemWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/Input/InputNodeWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ObjectOutput/ObjectOutputFieldWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ObjectOutput/ObjectOutputWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/PrimitiveOutput/PrimitiveOutputElementWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/PrimitiveOutput/PrimitiveOutputWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/QueryOutput/QueryOutputWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/commons/PrimitiveTypeInputWidget.tsx
> [Inline Data Mapper] Fetch Updated CodeData via Flow Model 

- workspaces/ballerina/ballerina-core/src/flow-model/BaseVisitor.ts
- workspaces/ballerina/ballerina-core/src/flow-model/flow-model-utils.ts
- workspaces/ballerina/ballerina-core/src/index.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/VariableFindingVisitor.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-extension/src/views/visualizer/webview.ts
- workspaces/ballerina/bi-diagram/src/components/Diagram.tsx
- workspaces/ballerina/bi-diagram/src/index.tsx
- workspaces/ballerina/bi-diagram/src/visitors/AddNodeVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/BreakpointVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/InitVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/LinkTargetVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/NodeFactoryVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/PositionVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/RemoveEmptyNodesVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/RemoveNodeVisitor.ts
- workspaces/ballerina/bi-diagram/src/visitors/SizingVisitor.ts
> [Inline Data Mapper] Use flow model visitor to filter variable declarations

- workspaces/ballerina/ballerina-side-panel/src/components/NodeList/index.tsx
- workspaces/ballerina/component-diagram/src/components/nodes/EntryNode/EntryNodeWidget.tsx
Add improvements to component diagram resource accessor and plus node menu
Related https://github.com/wso2/product-ballerina-integrator/issues/615
Related https://github.com/wso2/product-ballerina-integrator/issues/616
> Brief description of the new feature or bug fix …
> Add improvements to component diagram resource accessor and plus node menu

- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-agent/index.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-agent/rpc-type.ts
- workspaces/ballerina/ballerina-extension/src/core/extended-language-client.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-agent/rpc-handler.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-agent/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/utils/project-artifacts.ts
- workspaces/ballerina/ballerina-extension/src/utils/source-utils.ts
- workspaces/ballerina/ballerina-rpc-client/src/rpc-clients/ai-agent/rpc-client.ts
- workspaces/ballerina/ballerina-visualizer/src/constants.ts
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AIChatAgentWizard.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AgentConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/MemoryManagerConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/ModelConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/NewAgent.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/ToolConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/utils.ts
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/utils.ts
Addresses https://github.com/wso2/product-ballerina-integrator/issues/768
Changes include:
- Add RPC methods `agentManager/getAgentOrg` to get AI module organization.
- Update RPC methods `serviceDesign/getListenerModel`, `serviceDesign/getServiceModel`, `agentManager/getAllAgents`, `agentManager/getAllMemoryManagers` and `agentManager/getAllModels` to accept orgName parameter.
- Update AI Agent creation flow to support both `ballerina/ai` and `ballerinax/ai` packages.
- Update AI Chat Agent creation flow to support both `ballerina/ai` and `ballerinax/ai` packages.
- Remove hardcoded code injection for agent and model code in `agents.bal` when creating AI Chat Agent.
- Update `AgentConfig` and `ModelConfig` to support new `ballerina/ai` package.
- Move `getNodeTemplate` function to …
> Update AI Agent to Utilize New ballerina/ai Packages

- workspaces/ballerina/ballerina-extension/src/features/debugger/config-provider.ts
$subject. 
This should fix https://github.com/wso2/product-ballerina-integrator/issues/792
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> [BI] Fix run button when plugin dev mode is enabled

- workspaces/ballerina/type-editor/src/TypeEditor/TypeField.tsx
Reverts wso2/vscode-extensions#101
> Revert "Fix imported type validation issue"

- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-manager.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/utils/networkUtils.ts
> Retrieve STS token from platform extension to make copilot calls in cloud editor

- workspaces/ballerina/ballerina-visualizer/src/views/GraphQLDiagram/index.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/RecordEditor.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/Tabs/TypeCreatorTab.tsx
Fix for the issue https://github.com/wso2/product-ballerina-integrator/issues/814
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …
> Change the record name with context

- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-core/src/interfaces/inline-data-mapper.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-visualizer/src/views/InlineDataMapper/DataMapperView.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/LinkState/CreateLinkState.ts
> [Inline Data Mapper] Enable creating mappings within sub mapping views

- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-core/src/interfaces/inline-data-mapper.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-side-panel/src/components/Form/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGenerator/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGeneratorNew/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/InlineDataMapper/DataMapperView.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/InlineDataMapper/utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/DataMapper/SidePanel/SubMappingConfig/SubMappingConfigForm.tsx
- workspaces/ballerina/inline-data-mapper/src/index.tsx
- workspaces/ballerina/inline-data-mapper/src/store/store.ts
> [Inline Data Mapper] Enable create sub mappings with default values

- workspaces/mi/mi-extension/src/rpc-managers/mi-visualizer/rpc-manager.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/artifactTests/artifact.spec.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/components/ArtifactTest/BallerinaModule.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/components/UnitTest.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/components/Welcome.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/multiWorkspaceTests/multiWorkspace.spec.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/projectTests/createProject.spec.ts
> Fix MI E2E tests

- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/commandTemplates/data/commandTemplates.const.ts
Fix for the issue https://github.com/wso2/product-ballerina-integrator/issues/842
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Fix typo in copilot type creator command

- workspaces/ballerina/ballerina-extension/src/utils/project-artifacts.ts
> Enhance project artifact update logic to skip temporary directory files

- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-agent/index.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-agent/rpc-type.ts
- workspaces/ballerina/ballerina-extension/src/core/extended-language-client.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-agent/rpc-handler.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-agent/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/utils/project-artifacts.ts
- workspaces/ballerina/ballerina-extension/src/utils/source-utils.ts
- workspaces/ballerina/ballerina-rpc-client/src/rpc-clients/ai-agent/rpc-client.ts
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AIChatAgentWizard.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/MemoryManagerConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/ModelConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/NewAgent.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/utils.ts
Related to https://github.com/wso2/product-ballerina-integrator/issues/768
Changes include:
- Rename getAgentOrg API to getAiModuleOrg to account for this change in LS side: https://github.com/ballerina-platform/ballerina-language-server/pull/140
- Fix line range calculation in injectAIAgent function to remove extra line added when generating code for AI chat agent in `ballerinax` projects.
- Add Variables artifact type and corresponding directory mapping to fix the following error printed in console:
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to …
> [AI Features] Rename `getAgentOrg` API to `getAiModuleOrg`

- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/datamapper.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/schema.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/utils/attachment/attachmentManager.ts
This PR improves the schema used in `generateObject()` by wrapping the original `DataMappingSchema` in a top-level object. This change addresses a common issue with language model hallucination when generating deeply nested structures.
PR Resolves: [https://github.com/wso2/product-ballerina-integrator/issues/849](https://github.com/wso2/product-ballerina-integrator/issues/849)
* Defined new `MappingSchema`:
```ts
export const MappingSchema = z.object({
generatedMappings: DataMappingSchema,
});
```
* Replaced `DataMappingSchema` usage with `MappingSchema` in `generateObject()`.
* Updated the destructuring of the result to use `object.generatedMappings`.
> Describe how you are implementing …
> Change the DataMappingSchema to prevent hallucination

- workspaces/ballerina/inline-data-mapper/src/components/DataMapper/DataMapper.tsx
- workspaces/ballerina/inline-data-mapper/src/components/DataMapper/Header/DataMapperHeader.tsx
- workspaces/ballerina/inline-data-mapper/src/components/DataMapper/Header/ExpressionBar.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/commons/Search/SearchNoResultFound.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/commons/Search/index.tsx
- workspaces/ballerina/inline-data-mapper/src/store/store.ts
> [Inline Data Mapper] Minor improvements

- workspaces/ballerina/ballerina-core/src/interfaces/ai-panel.ts
- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-core/src/interfaces/inline-data-mapper.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-panel/index.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-panel/interfaces.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-panel/rpc-type.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/inline-utils.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-handler.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/utils.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
- workspaces/ballerina/ballerina-rpc-client/src/rpc-clients/ai-panel/rpc-client.ts
- workspaces/ballerina/ballerina-visualizer/src/utils/utils.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/commandTemplates/data/commandTemplates.const.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/commandTemplates/data/placeholderTags.const.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChat/Footer/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChat/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChatInput/index.tsx
- workspaces/ballerina/data-mapper-view/src/components/DataMapper/DataMapper.tsx
- workspaces/ballerina/inline-data-mapper/src/components/DataMapper/DataMapper.tsx
Added an AI chat flow to the Inline DataMapper with support for file attachments. This enhances user interaction and improves mapping accuracy by allowing context sharing within the chat.
Resolves: [https://github.com/wso2/product-ballerina-integrator/issues/789](https://github.com/wso2/product-ballerina-integrator/issues/789)
> Specify the reason if following are not …
> [AI Inline Datamapper] Implement AI chat flow for Inline Datamapper

- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/PanelManager.tsx
Fixes the issue: https://github.com/wso2/product-ballerina-integrator/issues/858
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter …
> Fix agent query not updating

- workspaces/mi/mi-visualizer/src/RuntimeServicesPanel.tsx
> Change default runtime state

- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/utils.ts
> [Inline Data Mapper] Enhance artifact search logic to support recursive matching

- workspaces/ballerina/inline-data-mapper/src/components/DataMapper/DataMapper.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Actions/IONodesScrollCanvasAction.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ArrayOutput/ArrayOuptutFieldWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ArrayOutput/OutputFieldPreviewWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/Input/InputNode.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/Input/InputNodeTreeItemWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/Input/InputNodeWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/LinkConnector/LinkConnectorNode.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/ObjectOutput/ObjectOutputFieldWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/PrimitiveOutput/PrimitiveOutputNode.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/PrimitiveOutput/PrimitiveOutputWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/QueryExprConnector/QueryExprConnectorNode.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/QueryExprConnector/QueryExprConnectorNodeWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/SubMapping/SubMappingItemWidget.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/Node/commons/DataMapperNode.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/common-utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/diagram-utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/link-utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/modification-utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/node-utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/search-utils.ts
> [Inline Data Mapper] Fixes related to diagram rendering and navigation

- workspaces/ballerina/ballerina-extension/src/features/config-generator/configGenerator.ts
- workspaces/ballerina/ballerina-extension/src/features/debugger/config-provider.ts
- workspaces/ballerina/ballerina-extension/src/features/project/cmds/run.ts
Fix for the issue https://github.com/wso2/product-ballerina-integrator/issues/169
Related backend changes are added with https://github.com/ballerina-platform/ballerina-language-server/pull/184
> Brief description of the new feature or bug fix as it will appear in the …
> [Ballerina Extension] Fix fast-run failures

- workspaces/ballerina/ballerina-core/src/interfaces/inline-data-mapper.ts
- workspaces/ballerina/ballerina-visualizer/src/views/InlineDataMapper/DataMapperView.tsx
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/modification-utils.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/utils/type-utils.ts
- Add module name for the type label in a field if available
- Additionally, refactor the expression bar completion filtering logic
> [BI Inline Data Mapper] Add module name for the type label

- workspaces/ballerina/ballerina-visualizer/src/constants.ts
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/ConfigForm.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
- workspaces/ballerina/bi-diagram/src/components/nodes/AgentCallNode/AgentCallNodeWidget.tsx
To resolve issues: 
- https://github.com/wso2/product-ballerina-integrator/issues/888
- https://github.com/wso2/product-ballerina-integrator/issues/890 …
> [AI Features] Fix broken Save functionality in ModelConfig form and rename model providers

- workspaces/ballerina/ballerina-core/src/rpc-types/ai-panel/index.ts
- workspaces/ballerina/ballerina-core/src/rpc-types/ai-panel/rpc-type.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/testGenerator.ts
- workspaces/ballerina/ballerina-extension/src/features/natural-programming/utils.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/inline-utils.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-handler.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/bi-diagram/rpc-manager.ts
- workspaces/ballerina/ballerina-rpc-client/src/rpc-clients/ai-panel/rpc-client.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/utils/networkUtils.ts
> $title.
Resolve issue caused by accessing legacy tokens after transition to BI Intel + Anthropic multi-auth support.
> Link(s) to product documentation that addresses the changes …
> Fix Visual Completion Failure with Updated Multi-Auth Token Management

- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AIAgentSidePanel.tsx
To address issue 2 in https://github.com/wso2/product-ballerina-integrator/issues/911.
- This change removes the `headers` and `addditionalValues` parameters from the tool inputs section when creating agent tool. Users will still have the option to add them back and configure them if required.
> Summary of user stories …
> [AI Features] Remove `headers` and `additionalValues` fields from agent tool inputs

- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/inline-data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
> Update frontend to handle the inline datamapper navigation

- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FocusFlowDiagram/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/Forms/ResourceForm/ResourceResponse/ResponseItem.tsx
Fixes: https://github.com/wso2/product-ballerina-integrator/issues/894
https://github.com/wso2/product-ballerina-integrator/issues/879
https://github.com/wso2/product-ballerina-integrator/issues/909
> Specify the …
> Update ResponseItem component to prioritize response and remove unnecessary identifier 

- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/constant.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/datamapper.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/inline_datamapper.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/inline_prompt.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/service/datamapper/types.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/inline-utils.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChat/index.tsx
Migrate inline datamapper backend logic to vscode extension side.
Resolves: [https://github.com/wso2/product-ballerina-integrator/issues/920](https://github.com/wso2/product-ballerina-integrator/issues/920)
> Brief description of the new feature or bug fix as it will …
> Migrate inline datamapper backend to extension side

- workspaces/mi/mi-extension/src/lang-client/activator.ts
> Fix synapse config formatting issue

- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AIChatAgentWizard.tsx
$subject
Addresses https://github.com/wso2/product-ballerina-integrator/issues/923
- Moved the initialization code to be executed after user clicks on "Save" button.
> Link(s) to …
> Refactor AIChatAgentWizard to pull missing modules after save button is clicked

- workspaces/ballerina/ballerina-visualizer/src/utils/bi.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/VectorKnowledgeBaseForm/index.tsx
Refactors the icon assignment logic in BI utility functions to handle cases where codedata is missing.
> Refactor icon assignment logic in BI utils

- workspaces/mi/mi-visualizer/src/views/Overview/ProjectInformation/ProjectInformationForm.tsx
$subject 
Fixes: https://github.com/wso2/mi-vscode/issues/1221
> Allow `ciphertool.enable` property to be updated thorugh Project Settings page

- workspaces/ballerina/data-mapper-view/src/components/Diagram/LinkState/CreateLinkState.ts
- workspaces/ballerina/inline-data-mapper/src/components/Diagram/LinkState/CreateLinkState.ts
- workspaces/mi/mi-data-mapper/src/components/Diagram/LinkState/CreateLinkState.ts
$title
Related to: https://github.com/wso2/product-ballerina-integrator/issues/196
> Fix creating many-to-one mappings by selecting output field using parial links

- workspaces/ballerina/ballerina-core/src/rpc-types/ai-agent/interfaces.ts
- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/AIAgentSidePanel.tsx
Addresses https://github.com/wso2/product-ballerina-integrator/issues/952
Changes Include:
- Refactor agent tool creation code to remove duplicate code.
- Fix resource path parameter not replaced by custom value in agent tool creation by updating `resourcePath` property in flownode being sent to `genTool` API.
> Summary …
> Fix resource path parameter not replaced by custom value in agent tool creation

- workspaces/ballerina/ballerina-visualizer/src/views/BI/DiagramWrapper/index.tsx
Fixes: https://github.com/wso2/product-ballerina-integrator/issues/965
> Brief description of the new feature or …
> Refactor diagram component to fix sequence diagram switch loader

- workspaces/ballerina/data-mapper-view/src/components/DataMapper/ConfigPanel/utils.ts
- workspaces/ballerina/data-mapper-view/src/components/Diagram/Node/FromClause/FromClauseNode.ts
- workspaces/ballerina/data-mapper-view/src/components/Diagram/Node/LinkConnector/LinkConnectorNode.ts
- workspaces/ballerina/data-mapper-view/src/components/Diagram/Node/RequiredParam/RequiredParamNode.ts
- workspaces/ballerina/data-mapper-view/src/components/Diagram/Node/RequiredParam/RequiredParamNodeFactory.tsx
- workspaces/ballerina/data-mapper-view/src/components/Diagram/Node/commons/DataMapperNode.ts
- workspaces/ballerina/data-mapper-view/src/components/Diagram/Node/commons/RecordTypeTreeWidget/RecordTypeTreeWidget.tsx
- workspaces/ballerina/data-mapper-view/src/components/Diagram/utils/dm-utils.ts
$title
Related issue: https://github.com/wso2/product-ballerina-integrator/issues/606
> [Ballerina Data Mapper] Enable create mappings within query expressions using nullable input fields

- .github/actions/pr/action.yml
> Fix PR creation failure

- workspaces/mi/mi-visualizer/src/views/Forms/IDPConnectorForm/IdpHeaderSchemaGeneration.tsx
- workspaces/mi/mi-visualizer/src/views/Forms/IDPConnectorForm/IdpHeaderTryout.tsx
- workspaces/mi/mi-visualizer/src/views/Forms/IDPConnectorForm/SchemaEditorView.tsx
> fix windows path issues

- workspaces/mi/mi-extension/package.json
- workspaces/mi/mi-extension/src/constants/index.ts
- workspaces/mi/mi-extension/src/debugger/debugHelper.ts
- workspaces/mi/mi-extension/src/debugger/tasks.ts
- workspaces/mi/mi-extension/src/test-explorer/runner.ts
- workspaces/mi/mi-extension/src/util/migrationUtils.ts
- workspaces/mi/mi-extension/src/util/templates.ts
- workspaces/mi/mi-visualizer/src/views/Overview/ProjectInformation/ProjectInformationForm.tsx
This PR will fix the issue https://github.com/wso2/mi-vscode/issues/1239
> Add an option to use locally installed maven within the extension

- workspaces/common-libs/ui-toolkit/src/components/Stepper/CompletedStepCard.tsx
- workspaces/common-libs/ui-toolkit/src/components/Stepper/IncompleteStepCard.tsx
- workspaces/common-libs/ui-toolkit/src/components/Stepper/Stepper.tsx
Addresses https://github.com/wso2/product-ballerina-integrator/issues/1044
- Fixes style breaking of the Stepper component when width is constrained.
- Fix StepCircle becoming oval-shaped by removing problematic positioning and using flexbox centering
- Align circles, text, and horizontal bars properly using align-items: center on StepCard
- Simplify StepNumber and RightSign positioning to use parent flexbox alignment
- Ensure consistent spacing and proper visual alignment for all step counts
Before:
After:
> Fix Stepper component alignment issues

- workspaces/mi/mi-extension/src/constants/index.ts
> Fix docker build issue on Windows OS

- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/utils/project-artifacts.ts
> Fix artifact notification not found issues in Copilot

- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/utils/project-artifacts.ts
> [Stable] Fix artifact notification not found issues in Copilot

- workspaces/ballerina/ballerina-side-panel/src/components/ParamManager/ParamManager.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/GraphQLDiagram/OperationForm.tsx
Related issue https://github.com/wso2/product-ballerina-integrator/issues/488
This pr adds the import detail to the parameter model which is required in the source generation
> …
> Add import property to parameter model

- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/Forms/ServiceConfigForm.tsx
Issue:  https://github.com/wso2/product-ballerina-integrator/issues/1067
The pr fixes the issue where the service model was not updating when user clear out the expression. 
Eg: when user removes the existing service configuration and save the form
> Brief description …
> Fix model content not properly updating on service edit

- workspaces/ballerina/ballerina-core/src/interfaces/data-mapper.ts
- workspaces/ballerina/ballerina-visualizer/src/Hooks.tsx
- workspaces/ballerina/ballerina-visualizer/src/MainPanel.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/DataMapper/DataMapperView.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/DataMapper/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/DataMapper/modelProcessor.ts
- workspaces/ballerina/data-mapper/src/components/DataMapper/DataMapperEditor.tsx
Related to:
https://github.com/wso2/product-ballerina-integrator/issues/1074
https://github.com/wso2/product-ballerina-integrator/issues/992
> [BI Data Mapper] Fix switching between different data mapper views

- workspaces/mi/mi-extension/package.json
- workspaces/mi/mi-extension/src/util/onboardingUtils.ts
> update car plugin automatically

- workspaces/ballerina/data-mapper/src/components/Diagram/Node/ArrayOutput/ArrayOuptutFieldWidget.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/Node/ObjectOutput/ObjectOutputFieldWidget.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/Node/PrimitiveOutput/PrimitiveOutputElementWidget.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/utils/modification-utils.ts
> Fixes https://github.com/wso2/product-ballerina-integrator/issues/1075
> [Data Mapper] Fix unable to delete array elements

- workspaces/ballerina/ballerina-visualizer/src/views/BI/Connection/ConnectorView/index.tsx
> Show message when no connectors found in current org

- workspaces/ballerina/data-mapper/src/components/Diagram/Node/QueryExprConnector/QueryExprConnectorNodeWidget.tsx
> Fix https://github.com/wso2/product-ballerina-integrator/issues/1093
> [Data Mapper] Fix link disappears in inner focused views

- workspaces/ballerina/ballerina-extension/webpack.config.js
- workspaces/ballerina/ballerina-visualizer/webpack.config.js
- workspaces/ballerina/persist-layer-diagram/webpack.config.js
- workspaces/ballerina/type-diagram/webpack.config.js
- workspaces/bi/bi-extension/webpack.config.js
- workspaces/choreo/choreo-extension/webpack.config.js
- workspaces/choreo/choreo-webviews/webpack.config.js
- workspaces/mi/mi-extension/webpack.config.js
- workspaces/wso2-platform/wso2-platform-extension/webpack.config.js
- workspaces/wso2-platform/wso2-platform-webviews/webpack.config.js
> Avoid sourcemaps in production build

- workspaces/ballerina/ballerina-visualizer/src/components/ConnectionSelector/ConnectionConfig.tsx
- workspaces/ballerina/ballerina-visualizer/src/components/ConnectionSelector/ConnectionCreator.tsx
- workspaces/ballerina/ballerina-visualizer/src/components/ConnectionSelector/config.ts
- workspaces/ballerina/ballerina-visualizer/src/components/ConnectionSelector/types.ts
- workspaces/ballerina/ballerina-visualizer/src/components/ConnectionSelector/utils.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Connection/ConnectionConfigView/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Connection/EditConnectionWizard/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/PanelManager.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/FormGenerator/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/VectorKnowledgeBaseForm/index.tsx
Addresses https://github.com/wso2/product-ballerina-integrator/issues/1019
Changes include:
- Refactor `VectorKnowledgeBaseForm` and remove hardcoded fields.
- Add option to reuse Vector Stores, Embedding Models and Chunkers.
- Update `EditConnectionWizard` for displaying connection selection and creation views similar to Flow Diagram side panel.
- Vector Knowledge Base creation flow:
https://github.com/user-attachments/assets/e54aac15-cd28-47a5-bb84-a2d769ae24b3
- Vector Knowledge Base edit flow:
https://github.com/user-attachments/assets/b2db7284-a475-4e75-862b-eab90483020f
> Summary …
> Update knowledge base creation with chunker support

- workspaces/ballerina/data-mapper/src/components/Diagram/utils/search-utils.ts
$title
Related to: https://github.com/wso2/product-ballerina-integrator/issues/1105
> [BI Data Mapper] Fix create mapping within filtered array elements 

- workspaces/ballerina/ballerina-visualizer/src/views/BI/Connection/ConnectorView/index.tsx
Add min width the left panel in connection view
Fixes https://github.com/wso2/product-ballerina-integrator/issues/1114
> Link(s) to product documentation that addresses the changes …
> Add min width to the left panel in connection view

- workspaces/ballerina/ballerina-visualizer/src/views/BI/FlowDiagram/index.tsx
- workspaces/ballerina/bi-diagram/src/components/nodes/IfNode/MatchNodeWidget.tsx
- Fixes an issue where the side panel fails to close after adding a new node.
- Corrects a problem where match statements caused the flow diagram to break.
- Addresses the inability to add an `ErrorHandler` node from the flow diagram.
Tasks
- https://github.com/wso2/product-ballerina-integrator/issues/1108
- https://github.com/wso2/product-ballerina-integrator/issues/1113
- https://github.com/wso2/product-ballerina-integrator/issues/1116
> Fix flow diagram and side panel issues

- workspaces/ballerina/ballerina-side-panel/src/components/Form/index.tsx
Related to: https://github.com/wso2/product-ballerina-integrator/issues/1145
> [BI Data Mapper] Fix rendering 'Open in Data Mapper' button for new variables

- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChat/index.tsx
$Subject
Blocker for the release
Resolves https://github.com/wso2/product-ballerina-integrator/issues/1184
> Link(s) to product documentation that addresses the changes of this PR. …
> Add states to temp file holder

- workspaces/ballerina/ballerina-extension/src/features/bi/activator.ts
Resolves: https://github.com/wso2/product-ballerina-integrator/issues/1191
> Brief description of the new …
> Comment out the openAllBallerinaFiles function call

- workspaces/ballerina/ballerina-extension/src/features/bi/activator.ts
- workspaces/ballerina/ballerina-side-panel/src/components/Form/index.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/ServiceWizard.tsx
$Subject &
Fixes: https://github.com/wso2/product-ballerina-integrator/issues/1182
> Brief description of the …
> Added missing sub panel open and fix initial project loading with ballerina.toml

- workspaces/ballerina/ballerina-visualizer/src/components/ConnectionSelector/ConnectionCreator.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/Forms/VectorKnowledgeBaseForm/index.tsx
Related to https://github.com/wso2/product-ballerina-integrator/issues/1019
Adds separator between form fields and variable field in vector knowledge base creation form and connection creator form (used for model providers). This was not visible earlier since `compact` prop was set to `true` in the `FormGeneratorNew` component.
> Specify the reason if following are not …
> Add separator between form fields and variable field in vector knowledge base creation form

- workspaces/ballerina/ballerina-core/src/interfaces/data-mapper.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/types.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/utils.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/data-mapper/utils.ts
Expands the `InputCategory` to support additional categories required for the enhanced data model and AI data mapper functionality.
- **Added new enum values:**
- `Enum = "enum"` - Support for enumerated value types
- `LocalVariable = "local-variable"` - Support for local scope variables
- **Updated existing enum value:**
- Changed `ModuleVariable = "moduleVariable"` to `ModuleVariable = "module-variable"` for consistent kebab-case naming
- **Updated AI data mapper integration** to recognize and handle all new InputCategory types
Resolves: [https://github.com/wso2/product-ballerina-integrator/issues/1183](https://github.com/wso2/product-ballerina-integrator/issues/1183)
> Describe how you …
> Support new types in input category

- workspaces/ballerina/ballerina-extension/src/features/tryit/utils.ts
$subject.
Addresses https://github.com/wso2/product-ballerina-integrator/issues/1171
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, …
> [BI] Improve service try-it debug logs

- workspaces/ballerina/data-mapper/src/components/Diagram/Node/SubMapping/SubMappingTreeWidget.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/utils/type-utils.ts
$title
Related to: https://github.com/wso2/product-ballerina-integrator/issues/1180
> [BI Data Mapper] Fix expanding record typed sub-mappings

- workspaces/ballerina/ballerina-extension/src/core/extension.ts
> Enhance Ballerina setup process with detailed debug logs

- workspaces/ballerina/data-mapper/src/components/Diagram/Node/Input/InputNodeTreeItemWidget.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/Node/Input/InputNodeWidget.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/Node/commons/DataMapperNode.ts
> Fix https://github.com/wso2/product-ballerina-integrator/issues/1208
> [BI Data Mapper] Fix unable to collapse focused inputs

- workspaces/ballerina/ballerina-visualizer/src/views/BI/FocusFlowDiagram/index.tsx
Addresses https://github.com/wso2/product-ballerina-integrator/issues/1207
Fixes np function prompt changing to previous value after updating/creating model provider.
https://github.com/user-attachments/assets/e829c8f9-8108-4770-aca1-e8cc7b54f2c1
> Brief description of …
> Fix np function prompt changing after model provider update

- workspaces/ballerina/ballerina-core/src/interfaces/data-mapper.ts
- workspaces/ballerina/ballerina-core/src/interfaces/extended-lang-client.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/data-mapper/utils.ts
- workspaces/ballerina/ballerina-visualizer/src/views/DataMapper/DataMapperView.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/utils/common-utils.ts
Related to: https://github.com/wso2/product-ballerina-integrator/issues/1187
> [BI Data Mapper] Fix navigate into query expressions defined within sub-mappings

- workspaces/ballerina/ballerina-extension/src/rpc-managers/data-mapper/utils.ts
> Temporary fix for https://github.com/wso2/product-ballerina-integrator/issues/1228, until https://github.com/wso2/product-ballerina-integrator/issues/912 is fixed from the LS side.
> [BI Data Mapper - Reusable] Fix map with custom function not creating the link

- workspaces/ballerina/ballerina-side-panel/src/components/editors/TypeEditor.tsx
https://github.com/wso2/product-ballerina-integrator/issues/1059
https://github.com/user-attachments/assets/e3a42f84-0ef4-4a91-8cca-d2cc40db9a75
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> [BI]Add diagnostics support

- workspaces/ballerina/type-editor/src/TypeEditor/AdvancedOptions.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/ClassEditor.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/EnumEditor.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/FieldEditor.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/RecordEditor.tsx
- workspaces/ballerina/type-editor/src/TypeEditor/UnionEditor.tsx
https://github.com/wso2/product-ballerina-integrator/issues/1209
https://github.com/user-attachments/assets/51afbd79-0baa-45e9-bc99-4e056b9e4f79
> Link(s) to product documentation that addresses the changes of this PR. If no doc …
> Add tooltips to buttons in the type-editor

- workspaces/ballerina/ballerina-core/src/utils/modification-utils.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/constants.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/rpc-manager.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/ai-panel/utils.ts
- workspaces/ballerina/ballerina-extension/src/rpc-managers/data-mapper/rpc-manager.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChat/index.tsx
This PR removes unused reserved keywords from the DataMapper model and fixes the issue of hallucinated mappings when no fields are available. Now, empty mappings are handled gracefully by returning `null` instead of generating invalid mappings.
It Resolves : https://github.com/wso2/product-ballerina-integrator/issues/1285
> Specify the reason if following are not …
> [AI Datamapper] Remove irrelevant reserved keywords and handle hallucination on empty mappings

- workspaces/ballerina/ballerina-visualizer/src/views/TypeDiagram/index.tsx
Fix for https://github.com/wso2/product-ballerina-integrator/issues/1308
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus …
> Fix addType opening a previously edited type form

- workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/components/Header/ExpressionEditor.tsx
> Address https://github.com/wso2/product-ballerina-integrator/issues/1314
> [BI Data Mapper] Fix expression bar completions not closing after a completion item select

- .github/workflows/publish-vsix.yml
- .github/workflows/release-vsix.yml
> Run release workflow in codebuild runner

- workspaces/ballerina/data-mapper/src/components/DataMapper/DataMapperEditor.tsx
- workspaces/ballerina/data-mapper/src/components/DataMapper/Header/DataMapperHeader.tsx
> Implement https://github.com/wso2/product-ballerina-integrator/issues/1317
> [BI Data Mapper] Improve back button behaviour

- workspaces/ballerina/ballerina-visualizer/src/views/BI/AIChatAgent/NewAgent.tsx
> Update fileName prop in AI Agent ConfigForm component to use the correct filename

- workspaces/ballerina/ballerina-extension/src/utils/state-machine-utils.ts
Fixes: https://github.com/wso2/product-ballerina-integrator/issues/1338
> Brief description of the new feature …
> Refactor findViewByArtifact function by removing drive letter normalization in windows

- workspaces/ballerina/data-mapper/src/components/DataMapper/Header/ExpressionBar.tsx
- workspaces/ballerina/data-mapper/src/components/Diagram/LinkState/DefaultState.ts
> Fix https://github.com/wso2/product-ballerina-integrator/issues/1345
> [Data Mapper] Fix expression bar remains active when it opened from context menu

- workspaces/bi/bi-extension/src/test/e2e-playwright-tests/test.list.ts
- workspaces/bi/bi-extension/src/test/e2e-playwright-tests/utils.ts
- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/test.list.ts
Fixes failing End-to-End (E2E) tests in the BI extension. The failure is caused by an unresolved module issue originating from the Ballerina distribution, which will be fixed in Ballerina 2201.13.0.
Fixed: https://github.com/wso2/product-ballerina-integrator/issues/1372
1.  **Workaround for Module Issue:** Temporarily pull the exact versions of the unresolved Ballerina libraries (e.g., `bal pull ballerina/task:2.7.0`) to unblock the E2E tests until the new Ballerina distribution is released.
2.  **Update:** Refactors test logging to improve readability.
> Fixes failing BI extension E2E tests

- workspaces/ballerina/data-mapper/src/components/DataMapper/DataMapperEditor.tsx
> Fix https://github.com/wso2/product-ballerina-integrator/issues/1337
> [Data Mapper] Fix context having outdated views array when root view modified

- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/Forms/FunctionConfigForm.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/components/AddServiceElementDropdown.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/components/ResourceAccordion.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/components/ResourceAccordionV2.tsx
- workspaces/ballerina/ballerina-visualizer/src/views/BI/ServiceDesigner/index.tsx
> Revamp Service Designer view with more organised Listener and Service Properties 

- workspaces/mi/mi-visualizer/src/views/Forms/APIform/index.tsx
$subject
Related to https://github.com/wso2/product-micro-integrator/issues/4100
> Improve API form with per API CORs settings 

- workspaces/mi/mi-extension/src/test/e2e-playwright-tests/components/ArtifactTest/APITests.ts
> Fix E2E tests

- workspaces/ballerina/data-mapper/src/components/DataMapper/Header/ExpressionBar.tsx
- workspaces/common-libs/ui-toolkit/src/components/ExpressionEditor/components/Header/ExpressionEditor.tsx
> Resolve https://github.com/wso2/product-ballerina-integrator/issues/1316
> [Data Mapper] handle ESC key behaviour in expression bar

- workspaces/ballerina/ballerina-extension/src/features/ai/service/code/code.ts
- workspaces/ballerina/ballerina-extension/src/features/ai/service/libs/text_editor_tool.ts
- workspaces/ballerina/ballerina-visualizer/src/views/AIPanel/components/AIChat/index.tsx
Related to https://github.com/wso2/product-ballerina-integrator/issues/1165
> Update assistant response for repair call with the newest version of `Vercel AI SDK`

- workspaces/ballerina/ballerina-extension/src/features/ai/utils.ts
> Update devant token env variables

- workspaces/ballerina/ballerina-extension/src/utils/server/server.ts
$title as this is packed with LS now
Addresses https://github.com/wso2/product-ballerina-integrator/issues/1009
> Add sqlite-jdbc to the exclusion list

- workspaces/ballerina/ballerina-extension/CHANGELOG.md
- workspaces/bi/bi-extension/CHANGELOG.md
> Update changelog for BI and Ballerina extensions and fixing formatting issues

- workspaces/ballerina/ballerina-extension/CHANGELOG.md
- workspaces/bi/bi-extension/CHANGELOG.md
> Remove test coverage details from BI extension changelog
